# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: OpenGL / SFML install
      run: |
        wget -O sfml.tar.gz https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
        mkdir -p sfml
        tar -xzf sfml.tar.gz -C sfml
        apt-get -y install freeglut3-dev

    - name: Build CMake
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Debug
        submodule-update: true
        configure-options: -DSFML_ROOT=sfml/SFML-2.5.1/lib/cmake/SFML
        #cc: # optional
        #cxx: # optional
        #target: # optional
        #build-options: # Misc Options to pass to CMake while building project using cmake --build, optional
